services:
  notary_url: "http://notary-service.build.10gen.cc:5000"

templates:
  deb:
    org: |
      Origin: mongodb
      Label: mongodb
      Suite: {{ .CodeName }}
      Codename: {{ .CodeName }}/mongodb-org
      Architectures: {{ .Architectures }}
      Components: {{ .Component }}
      Description: MongoDB packages
    enterprise: |
      Origin: mongodb
      Label: mongodb
      Suite: {{ .CodeName }}
      Codename: {{ .CodeName }}/mongodb-enterprise
      Architectures: {{ .Architectures }}
      Components: {{ .Component }}
      Description: MongoDB packages
  index_page: |
    <!DOCTYPE html>
    <html>
     <head>
       <title>{{ .Title }}</title>
     </head>

     <body>
       <table>
        <tr><td>
          <h1>{{ .Title }}</h1>
        </td></tr>

        <tr><td>
          <hr>
        </td></tr>

        <tr><td>
          <a href='..'>Parent Directory</a>
        </td></tr>

        {{ range $fn := .Files }}
        <tr><td>
          <a href='{{ $fn }}'>{{ $fn }}</a>
        </td></tr>
        {{ end }}

        <tr><td>
          <hr>
        </td></tr>

        <tr><td>
          <address>{{ .RepoName }}</address>
        </td></tr>
      </table>
     </body>
    </html>


repos:

####################
#
# Community Repos:
#
####################

  - name: rhel5
    type: rpm
    edition: org
    bucket: repo-test.mongodb.org
    prefix: yum/redhat/5
    repos:
      - yum/redhat/5
      - yum/redhat/5Server

  - name: rhel6
    type: rpm
    edition: org
    bucket: repo-test.mongodb.org
    repos:
      - yum/redhat/6
      - yum/redhat/6Server

  - name: rhel7
    type: rpm
    edition: org
    bucket: repo-test.mongodb.org
    repos:
      - yum/redhat/7
      - yum/redhat/7Server

  - name: amazon-2013.03
    type: rpm
    edition: org
    bucket: repo-test.mongodb.org
    repos:
      - yum/amazon/2013.03/mongodb-org

  - name: suse11
    type: rpm
    edition: org
    bucket: repo-test.mongodb.org
    repos:
      - zypper/suse/11/mongodb-org

  - name: suse12
    type: rpm
    edition: org
    bucket: repo-test.mongodb.org
    repos:
      - zypper/suse/12/mongodb-org

  - name: debian8
    type: deb
    code_name: "jessie"
    bucket: repo-test.mongodb.org
    edition: org
    component: main
    architectures:
      - amd64
    repos:
      - apt/debian/dists/jessie/mongodb-org

  - name: debian7
    type: deb
    code_name: "wheezy"
    bucket: repo-test.mongodb.org
    edition: org
    component: main
    architectures:
      - amd64
    repos:
      - apt/debian/dists/wheezy/mongodb-org

  - name: ubuntu1204
    type: deb
    code_name: "precise"
    edition: org
    bucket: repo-test.mongodb.org
    component: multiverse
    architectures:
      - amd64
    repos:
      - apt/ubuntu/dists/precise/mongodb-org

  - name: ubuntu1404
    type: deb
    code_name: "trusty"
    edition: org
    bucket: repo-test.mongodb.org
    component: multiverse
    architectures:
      - amd64
    repos:
      - apt/ubuntu/dists/trusty/mongodb-org

  - name: ubuntu1604
    type: deb
    code_name: "xenial"
    edition: org
    bucket: repo-test.mongodb.org
    component: multiverse
    architectures:
      - amd64
      - arm64
    repos:
      - apt/ubuntu/dists/xenial/mongodb-org

####################
#
# Enterprise Repos:
#
####################

  - name: rhel5
    type: rpm
    edition: enterprise
    bucket: repo-test.mongodb.com
    repos:
      - yum/redhat/5
      - yum/redhat/5Server

  - name: rhel6
    type: rpm
    edition: enterprise
    bucket: repo-test.mongodb.com
    repos:
      - yum/redhat/6
      - yum/redhat/6Server

  - name: rhel7
    type: rpm
    edition: enterprise
    bucket: repo-test.mongodb.com
    repos:
      - yum/redhat/7
      - yum/redhat/7Server

  - name: amazon-2013.03
    type: rpm
    edition: enterprise
    bucket: repo-test.mongodb.com
    repos:
      - yum/amazon/2013.03/mongodb-enterprise

  - name: suse11
    type: rpm
    edition: enterprise
    bucket: repo-test.mongodb.com
    repos:
      - zypper/suse/11/mongodb-enterprise

  - name: suse12
    type: rpm
    edition: enterprise
    bucket: repo-test.mongodb.com
    repos:
      - zypper/suse/12/mongodb-enterprise

  - name: debian8
    type: deb
    edition: enterprise
    code_name: "jessie"
    bucket: repo-test.mongodb.com
    component: main
    architectures:
      - amd64
      - ppc64el
      - s390x
    repos:
      - apt/debian/dists/jessie/mongodb-enterprise

  - name: debian7
    type: deb
    code_name: "wheezy"
    edition: enterprise
    component: main
    bucket: repo-test.mongodb.com
    architectures:
      - amd64
      - ppc64el
      - s390x
    repos:
      - apt/debian/dists/wheezy/mongodb-enterprise

  - name: ubuntu1204
    type: deb
    code_name: "precise"
    edition: enterprise
    bucket: repo-test.mongodb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
    repos:
      - apt/ubuntu/dists/precise/mongodb-enterprise

  - name: ubuntu1404
    type: deb
    code_name: "trusty"
    edition: enterprise
    bucket: repo-test.mongodb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
    repos:
      - apt/ubuntu/dists/trusty/mongodb-enterprise

  - name: ubuntu1504
    type: deb
    code_name: "vivid"
    edition: enterprise
    bucket: repo-test.mongodb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
    repos:
      - apt/ubuntu/dists/vivid/mongodb-enterprise

  - name: ubuntu1604
    type: deb
    code_name: "xenial"
    edition: enterprise
    bucket: repo-test.mongodb.com
    component: multiverse
    architectures:
      - arm64
      - amd64
      - ppc64el
      - s390x
    repos:
      - apt/ubuntu/dists/xenial/mongodb-enterprise
